const wordList = [
  "CAT","DOG","FISH","BIRD","BALL","TREE","BOOK","LOVE","HOME","STAR",
  "MOON","SUN","WIND","FIRE","WATER","EARTH","HAND","FOOT","NOSE","EYE",
  "APPLE","GRAPE","MANGO","BERRY","PIZZA","BREAD","RICE","CAKE","TEA","COFFEE",
  "SCHOOL","CLASS","TEACH","LEARN","WRITE","READ","STUDY","MATH","MUSIC","SPORT",
  "HAPPY","SMILE","SLEEP","DREAM","LAUGH","CRY","QUIET","LOUD","FAST","SLOW",
  "THANK","HELLO","SORRY","PLEASE","FRIEND","FAMILY","MOTHER","FATHER","SISTER","BROTHER",
  "CHAIR","TABLE","LIGHT","PHONE","PAPER","PEN","WATCH","CLOCK","BAG","SHOES",
  "HOUSE","ROOM","DOOR","WINDOW","WALL","FLOOR","CEILING","STAIRS","BED","SOFA",
  "ANIMAL","HORSE","SHEEP","COW","TIGER","LION","MONKEY","ZEBRA","MOUSE","RABBIT",
  "WORK","OFFICE","BOSS","MEETING","EMAIL","SALARY","TRAIN","BUS","CAR","PLANE"
];
